package Vista;

import Controlador.HomeControlador;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Sistema
     */
    
    HomeControlador homeControlador;
    Usuarios frmUsuarios;
    
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(Home.MAXIMIZED_BOTH);
        
        homeControlador = new HomeControlador(frmUsuarios, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jmAdminitracion = new javax.swing.JMenu();
        jmiUsuarios = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();
        jmHerramientas = new javax.swing.JMenu();
        jmiClientes = new javax.swing.JMenuItem();
        jmiProductos = new javax.swing.JMenuItem();
        jmiProveedores = new javax.swing.JMenuItem();
        jmEntradasSalidas = new javax.swing.JMenu();
        jmiEntradas = new javax.swing.JMenuItem();
        jmiSalidas = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setMinimumSize(new java.awt.Dimension(1040, 566));
        setPreferredSize(new java.awt.Dimension(1040, 566));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenuBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jmAdminitracion.setText("Administración");

        jmiUsuarios.setText("Usuarios");
        jmAdminitracion.add(jmiUsuarios);

        jmiSalir.setText("Salir");
        jmAdminitracion.add(jmiSalir);

        jMenuBar.add(jmAdminitracion);

        jmHerramientas.setText("Herramientas");

        jmiClientes.setText("Clientes");
        jmHerramientas.add(jmiClientes);

        jmiProductos.setText("Productos");
        jmHerramientas.add(jmiProductos);

        jmiProveedores.setText("Proveedores");
        jmHerramientas.add(jmiProveedores);

        jmEntradasSalidas.setText("E/S de productos");

        jmiEntradas.setText("Entradas de producto");
        jmEntradasSalidas.add(jmiEntradas);

        jmiSalidas.setText("Salidas de productos");
        jmEntradasSalidas.add(jmiSalidas);

        jmHerramientas.add(jmEntradasSalidas);

        jMenuBar.add(jmHerramientas);

        setJMenuBar(jMenuBar);

        setBounds(0, 0, 1056, 574);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jmAdminitracion;
    public javax.swing.JMenu jmEntradasSalidas;
    private javax.swing.JMenu jmHerramientas;
    public javax.swing.JMenuItem jmiClientes;
    public javax.swing.JMenuItem jmiEntradas;
    public javax.swing.JMenuItem jmiProductos;
    public javax.swing.JMenuItem jmiProveedores;
    public javax.swing.JMenuItem jmiSalidas;
    public javax.swing.JMenuItem jmiSalir;
    public javax.swing.JMenuItem jmiUsuarios;
    // End of variables declaration//GEN-END:variables
}
